server:
  port: 8081

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tmp}
    username: ${DATABASE_USERNAME:tmp}
    password: ${DATABASE_PASSWORD:tmp}
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "0123456789abcdef0123456789abcdef"
  issuer: "task-management"
  expiration-minutes: 120

app:
  kafka:
    topics:
      user-created: ${KAFKA_TOPIC_USER_CREATED:user.created}
      task-created: ${KAFKA_TOPIC_TASK_CREATED:task.created}
      task-completed: ${KAFKA_TOPIC_TASK_COMPLETED:task.completed}

outbox:
  poll-interval: 2s
  batch-size: 50
